AWSTemplateFormatVersion: "2010-09-09"
Description: Drink Tracker Serverless API

Parameters:
  DeploymentBucket:
    Type: String
    Description: S3 bucket containing the Lambda deployment package
  LambdaS3Key:
    Type: String
    Default: lambda.zip
    Description: S3 key for the Lambda deployment package

Resources:
  DrinkTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DrinkTracker
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt DrinkTable.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  DrinkLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: DrinkTrackerFunction
      Runtime: nodejs18.x
      Handler: src/handler.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref DeploymentBucket
        S3Key: !Ref LambdaS3Key
      Environment:
        Variables:
          TABLE_NAME: DrinkTracker

  ApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: DrinkTrackerApi
      ProtocolType: HTTP

  LambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiGateway
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt DrinkLambda.Arn
      PayloadFormatVersion: "2.0"

  ApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: "GET /drink"
      Target: !Join
        - /
        - - integrations
          - !Ref LambdaIntegration

  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ApiGateway
      StageName: prod
      AutoDeploy: true

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DrinkLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

Outputs:
  ApiEndpoint:
    Description: API Endpoint
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/drink"
